README.md
pyproject.toml
src/motor_task_prototype/__main__.py
src/motor_task_prototype/geometry.py
src/motor_task_prototype/task.py
tests/test_geometry.py
tests/test_psychopy.py

- user dialog to choose task settings
- Number of targets
- Order of targets
- Target Duration
- Interval between targets
- Distance of targets
- Size of targets
- Size of center point
- Audible tone
- Display cursor
- Display cursor path
- Rotate cursor
- display n radially-arrayed targets
- for each target
- move mouse cursor to centre of screen & disable moving it
- wait for a bit
- highlight one of the targets, optionally make an audible tone, enable mouse
- record mouse positions with timestamps until either the user moves cursor to target or timeout occurs

add initial implementation of basic task

---

src/motor_task_prototype/analysis.py
src/motor_task_prototype/geometry.py
src/motor_task_prototype/task.py
tests/test_geometry.py

- cache rotation angle instead of re-calculating for every mouse position
- add missing type annotations

minor refactor

---

.pre-commit-config.yaml
src/motor_task_prototype/__main__.py
src/motor_task_prototype/geometry.py
src/motor_task_prototype/task.py
tests/test_analysis.py
tests/test_geometry.py
tests/test_psychopy.py

- require all functions to have type annotations
- add missing / incorrect type annotations

add mypy pre-commit hook

---

.pre-commit-config.yaml
src/motor_task_prototype/__init__.py
src/motor_task_prototype/__main__.py
src/motor_task_prototype/setup.py
src/motor_task_prototype/trial.py
src/motor_task_prototype/vis.py

- on startup user can
- create and run a new trial
- import and re-run a trial from a psydat file
- import and display results from a psydat file
- after completing a trial
- user has option to save the results as a psydat file

wip add save/load functionality

---

benchmarks/profile_task.py
docs/notebooks/example.ipynb
src/motor_task_prototype/__init__.py
src/motor_task_prototype/__main__.py
src/motor_task_prototype/task.py
src/motor_task_prototype/vis.py

- previously we created a single psychopy Window
- this was used for the task and for the results display
- but on Windows it blocked dialog boxes from being displayed
- now the task and the results display create their own Window as needed
- when finished they close the Window
- resolves #38

always close window after use

---

codecov.yml
src/motor_task_prototype/trial.py
tests/test_trial.py

- move string to array conversion to validate_trial()
- add tests for validate_trial()
- reduce codecov required coverage to 50%

refactor trial validation

---

src/motor_task_prototype/__init__.py
src/motor_task_prototype/__main__.py
src/motor_task_prototype/setup.py
src/motor_task_prototype/task.py
src/motor_task_prototype/trial.py
src/motor_task_prototype/vis.py
tests/conftest.py
tests/test_task.py
tests/test_trial.py

- user can add multiple trials when creating an experiment
- resolves #24

support multiple blocks of trials

---

src/motor_task_prototype/setup.py
src/motor_task_prototype/task.py

- turns out this is what psychopy is using by default
- resolves #80

Use Qt instead of Wx for gui dialogs

---

src/motor_task_prototype/__init__.py
src/motor_task_prototype/__main__.py
src/motor_task_prototype/setup.py
src/motor_task_prototype/vis.py

- first ask which block of trials to display results from
- then either whole block, or a single trial from the block
- if there is only one block or one trial within the block the corresponding dialog is skipped
- resolves #71

ask user for condition & trial to display when displaying results

---

src/motor_task_prototype/__init__.py
src/motor_task_prototype/vis.py
tests/conftest.py
tests/test_vis.py

- fix `make_txt` in vis to return empty string if there is no data
- fix `experiment_with_results` tests fixture to generate the same data as the real task
- resolves #89

Fix bug when displaying missing data

---

src/motor_task_prototype/display_widget.py
src/motor_task_prototype/meta_widget.py
tests/test_display_widget.py
tests/test_meta_widget.py

- also refactor tests for display options widget

qt gui tests for MetadataWidget

---

src/motor_task_prototype/gui.py
src/motor_task_prototype/results_widget.py
src/motor_task_prototype/trials_widget.py
tests/test_results_widget.py
tests/test_trials_widget.py

- also rename
- `TrialListWidget` -> `TrialsWidget`
- `ResultListWidget` -> `ResultsWidget`

add qt gui tests of trials widget

---

src/motor_task_prototype/__init__.py
src/motor_task_prototype/gui.py
tests/test_gui.py

add minimal initial test of gui

---

src/motor_task_prototype/task.py

fix incorrect trial index used for display after each trial

---

src/vstt/__init__.py
src/vstt/common.py
src/vstt/experiment.py
src/vstt/stat.py
src/vstt/task.py
src/vstt/trial.py
src/vstt/types.py
tests/conftest.py
tests/test_trial.py

- bump version to 0.29.0
- resolves #195

Add `central_target_duration` to trial options

---

docs/developer/forwards-compatibility.rst
docs/index.rst

Add note on forwards compatibility to developer docs

---

docs/index.rst
docs/quickstart/create-experiment.rst
docs/reference/trial-conditions.rst
src/vstt/trial.py
src/vstt/vtypes.py

- rename `Trial settings` dialog to `Trial conditions`
- resolves #162

Add page to docs on trial conditions

---

docs/index.rst
docs/reference/trial-conditions.rst
src/vstt/task.py
src/vstt/vis.py
tests/test_task.py

- if condition_timeout is reached, current trial is no longer allowed to complete
- no data is recorded from this partially completed trial
- update docs
- resolves #225

Condition timeout stops trial

---

.github/workflows/cd.yml
.github/workflows/ci.yml
.pre-commit-config.yaml
CHANGELOG.md
src/vstt/__init__.py

- bump pre-commit / actions versions

Version 1.3.0

---

src/vstt/task.py

Set tone duration to 160ms

---

.pre-commit-config.yaml
src/vstt/__main__.py
src/vstt/display_widget.py
src/vstt/gui.py
src/vstt/meta_widget.py

- add scrollbars to metadata and display options in GUI
- start GUI as maximised

Improve GUI usability on low resolution screens
