README.md
RunPrototype.bat
UpdatePrototype.bat

- Provide windows shortcuts to
- Update/install prototype
- Run prototype
- These use the python environment installed by the standalone psychopy installer

add Windows install instructions

---

.github/workflows/ci.yml

- now test Python 3.7, 3.8, 3.9 on windows
- (one) difficulty with adding other python versions / operating systems is the lack of wxPython wheels

add more python versions to CI

---

pyproject.toml
src/motor_task_prototype/__main__.py
src/motor_task_prototype/task.py
src/motor_task_prototype/trial.py
tests/test_trial.py

- after each trial wait `post_trial_delay`
- unless it is the last trial of the block, then wait `post_block_delay`
- resolves #40
also
- separate trial import from trial validation
- use defaults for missing keys on import, but log a warning
- allows for basic forwards-compatibility of trials format

add delays after trial and block

---

.github/workflows/ci.yml
src/motor_task_prototype/__init__.py
src/motor_task_prototype/task.py
src/motor_task_prototype/vis.py
tests/conftest.py
tests/test_vis.py

- ElementArrayStim sizes should be array of `(x,y)` sizes for each element
- we were passing an array of scalar size values
- psychopy silently fixes this by converting it to a 2d array
- this conversion is buggy/ambiguous for 2 elements (`[s0,s1]` -> `[(s0,s1),(s0,s1)]` instead of `[(s0,s0),(s1,s1)]`)
- we now pass an array of `(s,s)` sizes instead of an array of `s`
- Add vis tests
- add conftest.py with a fixture to create a session scope wxPython Window for testing gui functions

fix bug in `make_targets` for 1 target and add vis tests

---

.github/workflows/ci.yml
pyproject.toml
tests/conftest.py
tests/test_vis.py

- use pyautogui library to generate mouse/keyboard events
- run each GUI function in a separate thread with delays between events to (hopefully) allow GUI to be ready
- resolves #50

add GUI tests

---

.github/workflows/ci.yml
.github/workflows/docs.yml
README.md
docs/developer/install.rst
pyproject.toml
src/motor_task_prototype/task.py
src/motor_task_prototype/vis.py
tests/conftest.py
tests/test_task.py
tests/test_vis.py

- add task GUI test
- include screenshots as ascii-art in pytest output to aid debugging
- add `winType` option whenever a psychopy `Window` is created to choose the backend
- default is still `pyglet`
- allows tests use `glfw` as it has better Xvfb support
- use threading instead of multiprocessing in gui interaction tests
- glfw backend works with threads and in fact had issues with multiple processes
- add linux CI config
- resolves #54

add GUI tests of task and linux CI

---

pyproject.toml
src/motor_task_prototype/__init__.py
src/motor_task_prototype/meta.py
src/motor_task_prototype/setup.py
src/motor_task_prototype/task.py
src/motor_task_prototype/trial.py
src/motor_task_prototype/vis.py
tests/conftest.py
tests/helpers/gui_test_utils.py
tests/test_meta.py
tests/test_task.py
tests/test_trial.py
tests/test_vis.py

add splash screen and metadata
- display splash screen with title and instructions before task begins
- add `MotorTaskMetadata`
- info about experiment, author, date, etc
- what text to show on splash screen
- add dialog to define this metadata at the start of new experiment setup
- resolves #41
also
- remove timeout for display_results screen, always wait for Enter keypress
- make keypress behaviour consistent everywhere:
- Enter closes current screen / continues to next screen
- Escape exits entire program

add splash screen and metadata

---

.pre-commit-config.yaml
src/motor_task_prototype/common.py
src/motor_task_prototype/display.py
src/motor_task_prototype/meta.py
src/motor_task_prototype/setup.py
src/motor_task_prototype/trial.py
src/motor_task_prototype/types.py
src/motor_task_prototype/vis.py
tests/test_display.py
tests/test_vis.py

- internally we use a TypedDict for metadata, trial and vis options for type safety
- when importing one of these from csv or psydat we get a plain dict, which may have missing or invalid keys
- on import we start with a valid TypedDict containing default values
- any keys present in the input dict overwrite the corresponding value
- defaults are used for keys missing from the input dict (and a warning is logged)
- invalid or unknown keys are ignored (and a warning is logged)
- refactor
- add types.py with TypedDict definitions
- add common.py with `import_typed_dict` utility function
- add display.py to deal with display options separately from vis.py

improve import of existing dicts

---

src/motor_task_prototype/vis.py
tests/helpers/gui_test_utils.py

- after display target function returns
- flip window to make it all grey
- instead of pressing enter once in separate thread to make target return
- keep pressing enter until screen is all grey
- should resolve flakiness on windows CI where tests hang after enter key event got lost and target never returns

make GUI vis tests more robust

---

.github/workflows/ci.yml
src/motor_task_prototype/display_widget.py
tests/conftest.py
tests/test_display_widget.py

- add workaround for qt xcb plugin crash caused by opencv-python env vars
- use `clicked` signal that gives a bool for the checked state of the checkbox instead of `stateChanged`

add first qt gui tests for DisplayOptionsWidget

---

src/motor_task_prototype/geom.py
src/motor_task_prototype/stat.py
src/motor_task_prototype/types.py
src/motor_task_prototype/vis.py
tests/conftest.py

- NDArray requires numpy >= 1.21 and provides minimal improvement over plain ndarray
- resolves #96

remove np.typing imports and NDArray use

---

src/motor_task_prototype/__main__.py
src/motor_task_prototype/gui.py
src/motor_task_prototype/meta_widget.py
src/motor_task_prototype/results_widget.py
tests/conftest.py
tests/helpers/gui_test_utils.py
tests/test_meta_widget.py
tests/test_results_widget.py
tests/test_vis.py

- add optional `--win-type` command line option for app
- add optional `win` and `win_type` parameters for widgets
- defaults are "pyglet" for `win_type` and `None` for `win`
- add tests of Window output for meta and results widgets

add `win` and `win_type` options everywhere

---

benchmarks/profile_task.py
src/motor_task_prototype/__init__.py
src/motor_task_prototype/display_widget.py
src/motor_task_prototype/experiment.py
src/motor_task_prototype/gui.py
src/motor_task_prototype/meta_widget.py
src/motor_task_prototype/results_widget.py
src/motor_task_prototype/stat.py
src/motor_task_prototype/task.py
src/motor_task_prototype/trial.py
src/motor_task_prototype/trials_widget.py
src/motor_task_prototype/types.py
src/motor_task_prototype/vis.py
tests/conftest.py
tests/helpers/gui_test_utils.py
tests/test_display_widget.py
tests/test_experiment.py
tests/test_gui.py
tests/test_meta_widget.py
tests/test_results_widget.py
tests/test_task.py
tests/test_trial.py
tests/test_trials_widget.py
tests/test_vis.py

- contains metadata, trial_list and display_options
- optionally also contains a TrialHandlerExt with results
- keeps track of the filename and if there are unsaved changes
- resolves #110
- saves/loads to/from a psychopy psydat file (which is just a pickled TrialHandlerExt object)
- call pickle directly if there are no results
- psychopy saveAsPickle function doesn't actually save anything unless there are results
- resolves #101
- fix inadvertent class variables that should have been instance variables
- except for any pyqt signals: these must be class variables

add Experiment class

---

.github/workflows/ci.yml
src/motor_task_prototype/__init__.py
src/motor_task_prototype/common.py
src/motor_task_prototype/experiment.py
src/motor_task_prototype/gui.py
tests/conftest.py
tests/helpers/qt_test_utils.py
tests/test_display.py
tests/test_experiment.py
tests/test_gui.py
tests/test_meta.py

- Experiment can save/load json or Excel files
- note: these do not include any results
- add file -> export menu item to GUI to export json/excel files
- add *.json, *.xlsx, *.* filters to file -> open
- resolves #28

add json and Excel format import/export options

---

src/motor_task_prototype/__init__.py
src/motor_task_prototype/meta.py
src/motor_task_prototype/meta_widget.py
src/motor_task_prototype/results_widget.py
src/motor_task_prototype/task.py
src/motor_task_prototype/trial.py
src/motor_task_prototype/types.py
src/motor_task_prototype/vis.py
tests/test_meta.py
tests/test_meta_widget.py
tests/test_trial.py
tests/test_vis.py

- add new options to trial
- `show_delay_countdown`: bool
- `enter_to_skip_delay`: bool
- add the same plus the duration to metadata
- `display_duration`: float
- `show_delay_countdown`: bool
- `enter_to_skip_delay`: bool
- extend metadata widget to deal with float / bool types
- refactor vis functionality
- resolves #135
- resolves #124
- resolves #123

add delay screen countdown and enter to skip options

---

src/motor_task_prototype/__init__.py
src/motor_task_prototype/experiment.py
src/motor_task_prototype/stat.py
src/motor_task_prototype/task.py
tests/conftest.py
tests/test_experiment.py

- add "statistics" sheet with all calculated statistics
- split (x,y) values into separate x, y columns
- add a sheet for each trial
- timestamps and mouse positions as vertical arrays of data
- split (x,y) values into separate x, y columns
- ignore these sheets when importing from Excel
- resolves #149
also
minor improvements to results data
- to_center_success is now True for automove_to_center experiments
- previously it was an empty array which prevented this column being imported as bool by pandas
- stack positions to explicitly make them 2d arrays instead of arrays of arrays

add statistics and raw results to Excel export

---

src/motor_task_prototype/__init__.py
src/motor_task_prototype/stat.py
src/motor_task_prototype/task.py
tests/test_stat.py

- include these movements in the displayed cursor paths
- include in the data with negative timestamps (where time = 0 is target display time)
- `reaction_time` can now be negative (if movement starts before target is displayed)
- `time` is still the time from target display to target reached
- `movement_time` is `time` minus `reaction_time`
- RMSE and distance measures include these movements
- resolves #150
also, while mouse cursor should be frozen:
- call `mouse.setPos()` with initial mouse position before each window flip
- minimises "jumping" of cursor when it is unfrozen
- resolves #156

Collect cursor movement before target is visible

---

.github/workflows/ci.yml
.pre-commit-config.yaml
pyproject.toml
src/motor_task_prototype/joystick_wrapper.py
src/motor_task_prototype/task.py
tests/conftest.py
tests/helpers/gui_test_utils.py
tests/test_task.py

- add `psychopy-sounddevice` to dependencies
- specify `stereo=True` in Sound()
- workaround for https://github.com/psychopy/psychopy-sounddevice/issues/2
- use pyglet backend instead of glfw in tests
- check `getNumJoysticks()` is non-zero before calling `Joystick(0)`
- psychopy previously raised an exception, but now just logs a warning
- resolves #168
also
- reduce post-block wait time in trials used in tests
- reduce mouse move time & pre-screenshot wait time in tests
- add pytest-randomly to test deps to randomise test execution order
- update ascii-magic use to use new v2 API
- add python 3.10 to CI jobs

add support for psychopy 2023.1.0

---

.pre-commit-config.yaml
docs/index.rst
docs/quickstart/create-experiment.rst
docs/quickstart/display-results.rst
docs/quickstart/install.rst
docs/quickstart/run-experiment.rst
docs/quickstart/share-experiment.rst
src/motor_task_prototype/experiment.py
src/motor_task_prototype/gui.py
src/motor_task_prototype/stat.py
tests/test_experiment.py
tests/test_gui.py

- save_excel(): add `data_format` option
- "trial": one page per trial
- "target": one page per target (previous behaviour)
- GUI
- ask user on excel export which option they want
- set "trial" as default
- excel format
- one page for a trial, with timestamps that increase throughout the trial
- for each timestamp, x/y mouse location, x/y target location, target index
- target index meaning:
- `non-negative`: index of visible outer target
- `-1`: center target is visible
- `99`: no targets visible
- target locations also set to `-99` if no target is visible
- docs
- add "Share experiments" page with info on import/export file formats
- resolves #172

Add excel data export option: one page per trial instead of per target

---

docs/quickstart/create-experiment.rst
src/motor_task_prototype/__init__.py
src/motor_task_prototype/task.py
src/motor_task_prototype/vis.py

- previous behaviour of this option was confusing and inconsistent
- new behaviour when `fixed_target_intervals=True` and `trial["target_duration"]=x`
- next outer target shown every `x` seconds
- this happens regardless of whether the user
- is moving to an outer target
- is moving to a central target
- has successfully moved to their target(s)
- update docs with this information
- resolves https://github.com/ssciwr/motor-task-prototype/issues/171

Fix `fixed_target_intervals` option

---

.github/workflows/ci.yml
.readthedocs.yml
README.md

- installs pre-built wxPython wheel & associated required system libs
- installs xvfb for a virtual display
- create 24bit screen as default 8bit screen not supported by opengl
- IMPORTANT: `DISPLAY=:0` env var is set in *web UI*
- installs mesa for software opengl support
- installs libportaudio2 for sounddevice support
- removes psychtoolbox after installing vstt to avoid psychtoolbox needing sudo issue
- resolves https://github.com/ssciwr/vstt/issues/62

add readthedocs config

---

docs/index.rst
docs/reference/framerate.rst
docs/reference/statistics.rst
src/vstt/__init__.py
src/vstt/gui.py
src/vstt/stat.py
src/vstt/task.py
tests/conftest.py
tests/test_experiment.py
tests/test_stat.py
tests/test_task.py

- use a single clock per trial starting from zero
- removes possibility of timestamps `fixed_target_intervals` drifting due to accumulated error
- resolves #198
- simplify logic and the conversion to excel timestamps
- add `to_target_num_timestamps_before_visible` int to trial data (and similarly for center)
- this is the number of to_target_timestamps for which the target is not yet visible
- previously this was implictly defined by these timestamps having negative values
- all timestamps are now taken directly after `window.flip()` returns
- this means the time is when the current frame was displayed (+maybe a few microseconds)
- and this frame remains displayed until the next timestamp
- previously we timestamped when we called `flip()` (which we control precisely)
- but this meant the …

Improve accuracy of timestamps

---

src/vstt/results_widget.py
src/vstt/task.py
src/vstt/trial.py
src/vstt/update.py
src/vstt/vtypes.py
tests/test_task.py
tests/test_trial.py

Add optional timeout for a set of conditions
- add `condition_timeout` to trial settings
- if `0` (default value) there is no timeout
- i.e. no change to existing behaviour
- if non-zero
- trials for this condition will stop after this time in seconds has elapsed
- if a trial is in progress when timeout occurs it is allowed to complete
- all subsequent trials from this condition are skipped
- update descriptions of trials to include timeout if present
- update stats / GUI to deal with missing data in trialhandler
- resolves #152

Add optional timeout for a set of conditions

---

pyproject.toml
src/vstt/results_widget.py
src/vstt/vis.py
tests/test_results_widget.py

- Add `Trial Image` and `Condition Image` buttons to results widget
- Screenshots visualization of results
- Prompts user for a filename to save the screenshot as a png image
- Add `return_screenshot` bool arg to `display_drawables` and `display_results`
- If true, do a single flip and then return image of window
- Default: `false`
- resolves #226

Add buttons to save image of results visualization

---

src/vstt/task.py
src/vstt/vis.py

- `display_results` and `display_drawables` optionally take a `mouse` and `mouse_pos`
- if supplied, it calls `mouse.setPos(mouse_pos)` before every flip
- used during the task to ensure mouse doesn't move while not visible during delays between trials/conditions
- resolves #234

Freeze mouse during delay between trials and conditions

---

src/vstt/display.py

- makes more sense to enable this now as default trial no longer auto-moves back to center

Enable display of to center paths by default

---

.github/workflows/ci.yml
CHANGELOG.md
src/vstt/__init__.py
src/vstt/task.py
tests/test_task.py

- repeat of condition with `fixed target display intervals` now continues the same fixed intervals
- previously the time from the last target of the previous trial was not taken into account
- this meant the first target of each repeat had a longer delay than desired
- store the time used by most recent target for current / previous trial in `TaskManager` to allow this
- extend `test_task_fixed_intervals_no_user_input` to include this case in tests
- bump version to 1.3.2
- update changelog
- resolves #256

Fix fixed target display intervals additional delay bug

---

.github/workflows/ci.yml
.pre-commit-config.yaml
src/vstt/task.py
tests/conftest.py
tests/test_geom.py
tests/test_meta_widget.py
tests/test_trial.py
tests/test_vis.py

- use pytest.approx for floating point comparisons
- replace legacy np.random.randint with rng.integers

Fix minor code smells

---

docs/notebooks/path_and_velocity.ipynb
pyproject.toml

1. Restrict the value of 2 variables "window-length" and "polyorder" in the example;
2. Set the numpy version < 2.0.0 in pyproject.toml

Restrict the value of 2 variables "window-length" and "polyorder" in the example, set the numpy version < 2.0.0 in pyproject.toml

---

.github/workflows/ci.yml
.pre-commit-config.yaml
CHANGELOG.md
docs/reference/trial-conditions.rst
src/vstt/__init__.py

- add Turn target green when reached to trial conditions docs
- update changelog
- bump version to 1.5.0

Version 1.5.0

---

pyproject.toml

- this is done by psychopy by default now
- remove psychopy-sounddevice from dependencies
- resolves 286

Use PTB for sounds instead of sounddevice
